let facturesState={liste:[],lignes:[],editionId:null};
function euroFacture(v){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(v)||0)}
function dateFacture(v){if(!v)return"";const d=new Date(v+"T00:00:00");return Number.isNaN(d.getTime())?v:d.toLocaleDateString("fr-FR")}
function initialiserFacturation(){if(document.body.dataset.facturationInitialisee)return;document.addEventListener("click",gererActionsFacturation);document.getElementById("factureSearch")?.addEventListener("input",afficherFactures);document.getElementById("factureForm")?.addEventListener("submit",e=>e.preventDefault());document.getElementById("factureClient")?.addEventListener("change",remplirClientFacture);document.getElementById("factureAddLine")?.addEventListener("click",()=>ajouterLigneFacture());document.body.dataset.facturationInitialisee="true"}
async function chargerFactures(){if(window.fbac)facturesState.liste=await window.fbac.obtenirFactures()}
function afficherFactures(){const t=document.getElementById("facturesTable");if(!t)return;const q=(document.getElementById("factureSearch")?.value||"").toLowerCase().trim();const l=facturesState.liste.filter(x=>[x.numero,x.client?.nom,x.client?.prenom,x.objet].join(" ").toLowerCase().includes(q));t.innerHTML=l.length?l.map(x=>"<tr><td><strong>"+echapperHtml(x.numero)+"</strong></td><td>"+dateFacture(x.date)+"</td><td>"+echapperHtml([x.client?.prenom,x.client?.nom].filter(Boolean).join(" ")||"—")+"</td><td>"+echapperHtml(x.objet||x.lignes?.[0]?.designation||"—")+"</td><td class='amount-positive'><strong>"+euroFacture(x.total)+"</strong></td><td><div class='actions'><button class='btn btn-small' data-facture-action='view' data-facture-id='"+x.id+"'>Voir</button><button class='btn btn-small' data-facture-action='print' data-facture-id='"+x.id+"'>Imprimer</button><button class='btn btn-small' data-facture-action='save' data-facture-id='"+x.id+"'>Enregistrer sous</button><button class='btn btn-small' data-facture-action='edit' data-facture-id='"+x.id+"'>Modifier</button><button class='btn btn-small button-danger' data-facture-action='delete' data-facture-id='"+x.id+"'>Suppr.</button></div></td></tr>").join(""):"<tr><td colspan='6' class='compta-empty'>Aucune facture enregistrée.</td></tr>"}
function remplirClientsFacture(){const s=document.getElementById("factureClient");if(!s)return;const p=[...(state.personnes||[])].sort((a,b)=>String(a.lastName||"").localeCompare(String(b.lastName||""),"fr"));s.innerHTML="<option value=''>Sélectionner un adhérent</option>"+p.map(x=>"<option value='"+echapperHtml(x.id)+"'>"+echapperHtml([x.lastName,x.firstName].filter(Boolean).join(" "))+"</option>").join("")}
function remplirClientFacture(){const p=(state.personnes||[]).find(x=>x.id===document.getElementById("factureClient")?.value);if(!p)return;document.getElementById("factureNom").value=p.lastName||"";document.getElementById("facturePrenom").value=p.firstName||""}
function ouvrirNouvelleFacture(){facturesState.editionId=null;facturesState.lignes=[];document.getElementById("factureModalTitle").textContent="Nouvelle facture";document.getElementById("factureForm").reset();document.getElementById("factureDate").value=new Date().toISOString().slice(0,10);remplirClientsFacture();ajouterLigneFacture();document.getElementById("factureModal").classList.add("active","open")}
function ajouterLigneFacture(l={}){facturesState.lignes.push({designation:l.designation||"",quantite:Number(l.quantite)||1,prixUnitaire:Number(l.prixUnitaire)||0,remise:Number(l.remise)||0});actualiserLignesFacture()}
function actualiserLignesFacture(){const z=document.getElementById("factureLines");if(!z)return;z.innerHTML=facturesState.lignes.map((l,i)=>"<div class='facture-line-editor' data-line-index='"+i+"'><div class='facture-line-field facture-line-designation'><label>Désignation</label><input type='text' placeholder='Ex. Forfait annuel adulte' value='"+echapperHtml(l.designation)+"' data-l='designation' data-i='"+i+"'></div><div class='facture-line-field'><label>Qté</label><input type='number' min='0' step='1' value='"+l.quantite+"' data-l='quantite' data-i='"+i+"'></div><div class='facture-line-field'><label>Prix unitaire</label><input type='number' min='0' step='0.01' value='"+l.prixUnitaire+"' data-l='prixUnitaire' data-i='"+i+"'></div><div class='facture-line-field'><label>Remise</label><input type='number' min='0' step='0.01' value='"+l.remise+"' data-l='remise' data-i='"+i+"'></div><div class='facture-line-total'><span>Total</span><strong>"+euroFacture(Math.max(0,l.quantite*l.prixUnitaire-l.remise))+"</strong></div><button type='button' class='btn btn-small button-danger' data-line-remove='"+i+"' "+(facturesState.lignes.length===1?"disabled":"")+">×</button></div>").join("");z.querySelectorAll("[data-l]").forEach(input=>input.addEventListener("input",()=>{const i=Number(input.dataset.i),k=input.dataset.l;facturesState.lignes[i][k]=k==="designation"?input.value:Number(input.value)||0;actualiserTotalLigneFacture(i)}));z.querySelectorAll("[data-line-remove]").forEach(b=>b.addEventListener("click",()=>{facturesState.lignes.splice(Number(b.dataset.lineRemove),1);actualiserLignesFacture()}));actualiserTotalFacture()}

function actualiserTotalLigneFacture(i){const l=facturesState.lignes[i];if(!l)return;const row=document.querySelector(".facture-line-editor[data-line-index='"+i+"']");if(row){const total=row.querySelector(".facture-line-total strong");if(total)total.textContent=euroFacture(Math.max(0,l.quantite*l.prixUnitaire-l.remise))}actualiserTotalFacture()}

function actualiserTotalFacture(){const total=facturesState.lignes.reduce((s,l)=>s+Math.max(0,l.quantite*l.prixUnitaire-l.remise),0);document.getElementById("factureFormTotal").textContent=euroFacture(total)}
function donneesFacture(){const sid=obtenirSaisonConsulteeId();return{date:document.getElementById("factureDate").value,saisonId:sid,saisonNom:state.saisons.find(x=>x.id===sid)?.nom||"",objet:document.getElementById("factureObjet").value.trim(),formuleDestinataire:document.getElementById("factureDestinataire").value.trim(),client:{personneId:document.getElementById("factureClient").value,nom:document.getElementById("factureNom").value.trim(),prenom:document.getElementById("facturePrenom").value.trim(),adresse:document.getElementById("factureAdresse").value.trim(),codePostal:document.getElementById("factureCodePostal").value.trim(),ville:document.getElementById("factureVille").value.trim(),siret:document.getElementById("factureSiretClient").value.trim()},lignes:facturesState.lignes}}
async function afficherApercuFacture(){try{const h=await window.fbac.apercuFacture(donneesFacture());document.getElementById("facturePreviewFrame").srcdoc=h;document.getElementById("factureModal").classList.remove("active","open");document.getElementById("facturePreviewModal").classList.add("active","open")}catch(e){notificationErreur(e.message||"Impossible de préparer l'aperçu.")}}
function fermerApercuFacture(){document.getElementById("facturePreviewModal").classList.remove("active","open");document.getElementById("factureModal").classList.add("active","open")}
async function validerFacture(){try{const d=donneesFacture();if(!d.client.nom&&!d.client.prenom)throw new Error("Sélectionnez ou renseignez un client.");const x=facturesState.editionId?await window.fbac.modifierFacture(facturesState.editionId,d):await window.fbac.creerFacture(d);document.getElementById("facturePreviewModal").classList.remove("active","open");facturesState.editionId=null;await chargerFactures();afficherFactures();notificationSucces("Facture "+x.numero+" générée.")}catch(e){notificationErreur(e.message||"Impossible de générer la facture.")}}
function modifierFactureInterface(id){const x=facturesState.liste.find(y=>y.id===id);if(!x)return;facturesState.editionId=id;document.getElementById("factureModalTitle").textContent="Modifier la facture "+x.numero;remplirClientsFacture();document.getElementById("factureClient").value=x.client?.personneId||"";document.getElementById("factureNom").value=x.client?.nom||"";document.getElementById("facturePrenom").value=x.client?.prenom||"";document.getElementById("factureAdresse").value=x.client?.adresse||"";document.getElementById("factureCodePostal").value=x.client?.codePostal||"";document.getElementById("factureVille").value=x.client?.ville||"";document.getElementById("factureSiretClient").value=x.client?.siret||"";document.getElementById("factureDate").value=x.date||"";document.getElementById("factureObjet").value=x.objet||"";document.getElementById("factureDestinataire").value=x.formuleDestinataire||"";facturesState.lignes=(x.lignes||[]).map(y=>({...y}));actualiserLignesFacture();document.getElementById("factureModal").classList.add("active","open")}
async function supprimerFactureInterface(id){const x=facturesState.liste.find(y=>y.id===id);if(!x||!confirm("Supprimer définitivement la facture "+x.numero+" ?\nLe fichier PDF sera également supprimé."))return;try{await window.fbac.supprimerFacture(id);await chargerFactures();afficherFactures();notificationSucces("Facture supprimée.")}catch(e){notificationErreur(e.message||"Impossible de supprimer la facture.")}}
async function ouvrirFactureInterface(id){const facture=facturesState.liste.find(x=>x.id===id);if(!facture)return;try{const h=await window.fbac.apercuFacture(facture);document.getElementById("facturePreviewFrame").srcdoc=h;document.getElementById("facturePreviewModal").classList.add("active","open")}catch(e){notificationErreur(e.message||"Impossible d'afficher la facture.")}}
function gererActionsFacturation(e){const a=e.target.closest("[data-facture-action]");if(a){const id=a.dataset.factureId,act=a.dataset.factureAction;if(act==="new")ouvrirNouvelleFacture();if(act==="preview")afficherApercuFacture();if(act==="view")ouvrirFactureInterface(id);if(act==="print")window.fbac.imprimerFacture(id);if(act==="save")window.fbac.enregistrerFactureSous(id);if(act==="edit")modifierFactureInterface(id);if(act==="delete")supprimerFactureInterface(id)}const g=e.target.closest("[data-action]");if(g?.dataset.action==="facture-confirm")validerFacture();if(g?.dataset.action==="facture-back-preview")fermerApercuFacture()}
async function afficherPageFacturation(){initialiserFacturation();await chargerFactures();afficherFactures()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialiserFacturation);else initialiserFacturation();